### ISSUE TITLE
Plex doesn't track Now Playing status for Sonos and (Marantz) network amplifier sessions

### ISSUE THREAD

**Issue by solid38** [glitch452/MMM-PlexNowPlaying#1]
Hi,

Thanks for your work.
Nevertheless, when I play a track with my network amplifier (Marantz M-CR611) or with my Sonos Play:1, no information has been displayed. 
When I play a track (or film, serie....), information has been weel displayed in my mirror.

Best regards.

**Comment by glitch452** [comment]
Hello,

Unfortunately I don't have a Sonos system or an amplifier that supports Plex playback, so I can't test those devices directly.  However, if you can post the data that shows up on the Plex server when you are streaming to those devices, I should be able to troubleshoot or add support for them.  

Please goto the following address and then put a comment here with the XML data that shows up:
<your_server_IP>:<your_server_port>/status/sessions/?X-Plex-Token=<your_plex_token>

**Comment by solid38** [comment]
When I test URL, I have this response : 
< MediaContainer size="0" >< / MediaContainer >

However, I currently have a song listening on my network amplifier.
Nevertheless, Plex does not see that there is currently a song listening .... so the problem comes from reading that does not seem to be detected by Plex ... weird.

**Comment by glitch452** [comment]
Hmm, that's what I was afraid of.  I wonder if there might be another endpoint on the Plex server for that kind of thing.  Does the stream show up in your Plex dashboard?

**Comment by solid38** [comment]
No, nothing appears. That why nothing appears in magic mirror with your module.

**Comment by glitch452** [comment]
I've done some searching and I can't find anything on the limited API documentation about another place to get now playing information.  I'm wondering if any non-Plex clients don't show up in the "Now Playing" list.  Unfortunately I won't be able to get that info into this module.

**Comment by solid38** [comment]
Thanks for all.
Have a nice day ;)

**Comment by TATUMTOT** [comment]
Your amp is probably using DLNA to access the files. I normally disable this.
