### ISSUE TITLE
MagicMirror2 not loading with module

### ISSUE THREAD

**Issue by jeffvader84** [glitch452/MMM-PlexNowPlaying#3]
I added the module to my MagicMirror and when I rebooted it shows me an error message stating I have an error in my config file or I don't have a config file.  I tried changing the settings from https to http and I tried both the DNS and IP address for my server, but MM2 still opened with the error.  The only thing that fixed it was to completely remove the module from the config file.  Any thoughts?  This module looks great and I would love to use it!  

Only other thing I can think of is after I downloaded the module into my modules folder I did an npm install command while in the directory MMM=PlexNowPlaying, which is what most modules have in their readme file.  Noticed after your readme didn't say to do that.  Help!  Thank you!

**Comment by jeffvader84** [comment]
Figured it out

**Comment by TATUMTOT** [comment]
What was the fix?

**Comment by jeffvader84** [comment]
Didn't notice the ... in your module text I copied into my config file.  So, the fix was to stop being stupid.  Thanks for checking in so fast on my issue!  Your module is awesome!

**Comment by TATUMTOT** [comment]
Not mine it is all @glitch452 just waiting for it to work in electron. Or what ever the browser is that MM using.

**Comment by glitch452** [comment]
It does work in Electron, just not with HTTPS, try HTTP and it should be good!

**Comment by TATUMTOT** [comment]
> It does work in Electron, just not with HTTPS, try HTTP and it should be good!

I cant or won't. Why would it not work with https?

**Comment by glitch452** [comment]
I'm not sure why it doesn't work with https.  Since its on my local network I didn't bother digging in to it.

**Comment by TATUMTOT** [comment]
Ya I force encryption and I had it working at some point with the chrome browser but then I read some ware it didn't work with the other browser just yet. But I will have to play with it. Or pass it thought a proxy locall or somthing. But it should work via https though. Wounder if it is Certificat authority related
