### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by eriecableguy** [glitch452/MMM-PlexNowPlaying#5]
I am only getting 

PLEX: NOW PLAYING
Plex Data ....

Maybe Im missing something ?

**Comment by glitch452** [comment]
Can you give some more info?  

A photo or screen shot of the output? 
The config options used (NOT your Plex token)?  
Goto the following address and get the XML data that shows up:
`<your_server_IP>:<your_server_port>/status/sessions/?X-Plex-Token=<your_plex_token>`

**Comment by eriecableguy** [comment]
![20200330_151446](https://user-images.githubusercontent.com/6271342/77953045-a232f500-729a-11ea-8ea2-e4d22dde590c.jpg)
![20200330_151524_2](https://user-images.githubusercontent.com/6271342/77953064-ab23c680-729a-11ea-8e53-bad69fb1b601.jpg)

**Comment by eriecableguy** [comment]
Ok, everytime I go through the motions to get my Token from Plex, it changes...

**Comment by eriecableguy** [comment]
I do show XML data in that link now..... But MM still shows the same message

**Comment by glitch452** [comment]
Can you post the XML data here, preferably when you're playing something.

For the Plex token, you can have multiple active ones.  I believe it is a token per player, so if you invalidate the player on the server, you would need a new token.

**Comment by eriecableguy** [comment]
This XML file does not appear to have any style information associated with
it. The document tree is shown below.
<MediaContainer size="1" allowSync="1" identifier="
com.plexapp.plugins.library" librarySectionID="3" librarySectionTitle="
Movies" librarySectionUUID="8cc4b0fc-0428-411a-9b12-fcdef1d1d2f1"
mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1585163346">
<Video ratingKey="11916" key="/library/metadata/11916" guid="
com.plexapp.agents.themoviedb://2665?lang=en" studio="Paramount" type="movie
" title="Airplane II: The Sequel" librarySectionTitle="Movies"
librarySectionID="3" librarySectionKey="/library/sections/3" contentRating="
PG" summary="A faulty computer causes a passenger space shuttle to head
straight for the sun, and man-with-a-past, Ted Striker must save the day
and get the shuttle back on track – again – all the while trying to patch
up his relationship with Elaine." rating="6.0" year="1982" tagline="For the
ride of your life... All you need for Christmas are your two front seats!"
thumb="/library/metadata/11916/thumb/1571088464" art="
/library/metadata/11916/art/1571088464" duration="5056052"
originallyAvailableAt="1982-12-10" addedAt="1571088129" updatedAt="
1571088464" chapterSource="media" hasPremiumPrimaryExtra="1">
<Media id="27753" duration="5056052" bitrate="10172" width="1280" height="
720" aspectRatio="1.78" audioChannels="2" audioCodec="flac" videoCodec="h264
" videoResolution="720" container="mkv" videoFrameRate="24p" videoProfile="
high">
<Part accessible="1" exists="1" id="27768" key="
/library/parts/27768/1390892996/file.mkv" duration="5056052"
file="D:\Videos\Movies\Airplane
II - The Sequel (1982)\Airplane II - The Sequel (1982).mkv" size="6430399283
" container="mkv" deepAnalysisVersion="4" hasThumbnail="1"
requiredBandwidths="
2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647
" videoProfile="high">
<Stream id="57635" streamType="1" default="1" codec="h264" index="0" bitrate
="9380" language="English" languageCode="eng" bitDepth="8" chromaLocation="
left" chromaSubsampling="4:2:0" colorPrimaries="bt709" colorRange="tv"
colorSpace="bt709" colorTrc="bt709" frameRate="23.976" hasScalingMatrix="0"
height="720" level="41" profile="high" refFrames="9" requiredBandwidths="
13838,12812,11127,10617,10200,10034,9794,9794" scanType="progressive" title
="Airplane II. The Sequel 1982 720p BluRay FLAC x264-SbR" width="1280"
displayTitle="720p (H.264)"/>
<Stream id="57636" streamType="2" selected="1" default="1" codec="flac"
index="1" channels="2" bitrate="792" language="English" languageCode="eng"
audioChannelLayout="stereo" bitDepth="24" requiredBandwidths="
836,836,836,836,836,836,836,836" samplingRate="48000" title="FLAC 2.0 @ 792
kbps" displayTitle="English (FLAC Stereo)"/>
<Stream id="57637" streamType="3" codec="srt" index="2" bitrate="0" language
="English" languageCode="eng" requiredBandwidths="1,1,1,1,1,1,1,1"
displayTitle="English (SRT)"/>
</Part>
</Media>
<Genre id="33610" filter="genre=33610" tag="Comedy"/>
<Director id="57548" filter="director=57548" tag="Ken Finkleman"/>
<Writer id="57549" filter="writer=57549" tag="Ken Finkleman"/>
<Country id="33614" filter="country=33614" tag="USA"/>
<Collection id="65268" filter="collection=65268" tag="Airplane"/>
<Role id="47833" filter="actor=47833" tag="Robert Hays" role="Ted Striker"
thumb="http://image.tmdb.org/t/p/original/1KWB4DXcsTVNDkDOaTJYatiTmDn.jpg"/>
<Role id="57559" filter="actor=57559" tag="Julie Hagerty" role="Elaine
Dickinson" thumb="
http://image.tmdb.org/t/p/original/3L0l8TVSzqYNmJA1b2Ve6bU2iwz.jpg"/>
<Role id="38692" filter="actor=38692" tag="Lloyd Bridges" role="Steven
McCroskey" thumb="
http://image.tmdb.org/t/p/original/qez0xZiQGt3f530vAGcoYAWd7FM.jpg"/>
<Role id="57550" filter="actor=57550" tag="Chad Everett" role="Simon Kurtz"
thumb="http://image.tmdb.org/t/p/original/tutl3qppeN8rbxO7mMJAu9SUCjV.jpg"/>
<Role id="43168" filter="actor=43168" tag="Peter Graves" role="Capt.
Clarence Oveur" thumb="
http://image.tmdb.org/t/p/original/sR9B0mE399EGI9aRxMbWMpk2GKT.jpg"/>
<Role id="57551" filter="actor=57551" tag="Chuck Connors" role="The Sarge"
thumb="http://image.tmdb.org/t/p/original/bBjFRL4ULfnegDMU6iNKBwS4IVj.jpg"/>
<Role id="49025" filter="actor=49025" tag="William Shatner" role="Cdr. Buck
Murdock" thumb="
http://image.tmdb.org/t/p/original/4byp8PsbRkC3UQVuvMAh4bcj7E2.jpg"/>
<Role id="46351" filter="actor=46351" tag="Raymond Burr" role="Judge D.C.
Simonton" thumb="
http://image.tmdb.org/t/p/original/Asn6aKAPshAUDnJN3OMLsBWCRwO.jpg"/>
<Role id="37754" filter="actor=37754" tag="John Vernon" role="Dr. Stone"
thumb="http://image.tmdb.org/t/p/original/8jESb02RChcuBEh4yZrLHElNhWa.jpg"/>
<Role id="57560" filter="actor=57560" tag="Kent McCord" role="Dave Unger"
thumb="http://image.tmdb.org/t/p/original/9ZrPhRZvwQEhrURXLfM4mRqbFXC.jpg"/>
<Role id="57556" filter="actor=57556" tag="James A. Watson, Jr" role="First
Officer Dunn" thumb="
http://image.tmdb.org/t/p/original/6IcFdczR0XEvLGJXyaHbvzZYuuu.jpg"/>
<Role id="57557" filter="actor=57557" tag="John Dehner" role="The
Commissioner" thumb="
http://image.tmdb.org/t/p/original/2maCnzFC38ACrrAtFOCMj0GoQ8V.jpg"/>
<Role id="43174" filter="actor=43174" tag="Rip Torn" role="Bud Kruger /
President Reagan" thumb="
http://image.tmdb.org/t/p/original/rzGaoGikjMuLDruABKdLcQLtkZk.jpg"/>
<Role id="57566" filter="actor=57566" tag="Sonny Bono" role="Joe Seluchi"
thumb="http://image.tmdb.org/t/p/original/kOFuou8PBht8nEVlFUlXvNzgne6.jpg"/>
<Role id="57567" filter="actor=57567" tag="Stephen Stucker" role="Jacobs /
Courtroom Clerk"/>
<Role id="57562" filter="actor=57562" tag="Laurene Landon" role="Testa"
thumb="http://image.tmdb.org/t/p/original/fbfnkFJm8CMIg1ae8zFMx4MA5y7.jpg"/>
<Role id="57565" filter="actor=57565" tag="Richard Jaeckel" role="Controller
#2" thumb="
http://image.tmdb.org/t/p/original/4pTd7yoDD46xbFcMuFHh8k448Um.jpg"/>
<Role id="35903" filter="actor=35903" tag="Lee Bryant" role="Mrs. Hammen"
thumb="http://image.tmdb.org/t/p/original/riFEbXO78dRCTxzQ358AVr1m4uD.jpg"/>
<Role id="57558" filter="actor=57558" tag="John Larch" role="Prosecuting
Attorney" thumb="
http://image.tmdb.org/t/p/original/dshTTCylpXofjXYsTefOOa9WSSe.jpg"/>
<Role id="46368" filter="actor=46368" tag="Sandahl Bergman" role="Officer #1
" thumb="http://image.tmdb.org/t/p/original/autibegxGq7oVvR5DGfEQL3ARoE.jpg"
/>
<Role id="57552" filter="actor=57552" tag="David Leisure" role="Religious
Zealot" thumb="
http://image.tmdb.org/t/p/original/rEyz16UwSZWoYahJw78Pg4BxLjv.jpg"/>
<Role id="57561" filter="actor=57561" tag="Kitten Natividad" role="Moral
Majority Woman (uncredited)" thumb="
http://image.tmdb.org/t/p/original/m3wYX0x4ED2shOSYxJ0lqyLvT65.jpg"/>
<Role id="57564" filter="actor=57564" tag="Monique Gabrielle" role="Schoolgirl
(uncredited)" thumb="
http://image.tmdb.org/t/p/original/jIlS9UmmvOoX2Pu0MWPHX05LQrB.jpg"/>
<Role id="57553" filter="actor=57553" tag="George Wendt" role="Ticket Agent
(uncredited)" thumb="
http://image.tmdb.org/t/p/original/wbDxe198w5Yu8zYdxkV9vmexN1E.jpg"/>
<Role id="57555" filter="actor=57555" tag="Jack Jones" role="Lounge Singer"
thumb="http://image.tmdb.org/t/p/original/fyfpRuM2Xx46HKzDmbe1oSyMNFd.jpg"/>
<Role id="57554" filter="actor=57554" tag="Hervé Villechaize" role="Little
Breather"/>
<Role id="57563" filter="actor=57563" tag="Madeleine Fisher" role="Shuttle
Agent"/>
<Similar id="57568" filter="similar=57568" tag="Airplane!"/>
<Similar id="57573" filter="similar=57573" tag="Naked Gun 33⅓: The Final
Insult"/>
<Similar id="57581" filter="similar=57581" tag="The Naked Gun 2½: The Smell
of Fear"/>
<Similar id="57577" filter="similar=57577" tag="Spy Hard"/>
<Similar id="57571" filter="similar=57571" tag="Hot Shots!"/>
<Similar id="33639" filter="similar=33639" tag="Stripes"/>
<Similar id="57572" filter="similar=57572" tag="Hot Shots! Part Deux"/>
<Similar id="57583" filter="similar=57583" tag="Top Secret!"/>
<Similar id="57575" filter="similar=57575" tag="National Lampoon's Loaded
Weapon 1"/>
<Similar id="57574" filter="similar=57574" tag="National Lampoon's European
Vacation"/>
<Similar id="57576" filter="similar=57576" tag="Spies Like Us"/>
<Similar id="57582" filter="similar=57582" tag="The Naked Gun: From the
Files of Police Squad!"/>
<Similar id="57580" filter="similar=57580" tag="The Man with Two Brains"/>
<Similar id="57578" filter="similar=57578" tag="The Cannonball Run"/>
<Similar id="57569" filter="similar=57569" tag="Cocoon"/>
<Similar id="33642" filter="similar=33642" tag="The Jewel of the Nile"/>
<Similar id="57570" filter="similar=57570" tag="Fletch Lives"/>
<Similar id="56496" filter="similar=56496" tag="Wayne's World 2"/>
<Similar id="65269" filter="similar=65269" tag="History of the World: Part I
"/>
<Similar id="33635" filter="similar=33635" tag="Innerspace"/>
<Chapter id="50744" filter="thumb=50744" tag="Maiden Voyage" index="1"
startTimeOffset="489000" endTimeOffset="996000" thumb="
/library/media/27753/chapterImages/1"/>
<Chapter id="50738" filter="thumb=50738" tag="A Madman On The Loose" index="
2" startTimeOffset="996000" endTimeOffset="1200000" thumb="
/library/media/27753/chapterImages/2"/>
<Chapter id="50748" filter="thumb=50748" tag="Oveur, Under" index="3"
startTimeOffset="1200000" endTimeOffset="1385000" thumb="
/library/media/27753/chapterImages/3"/>
<Chapter id="50743" filter="thumb=50743" tag="Liftoff" index="4"
startTimeOffset="1385000" endTimeOffset="1884000" thumb="
/library/media/27753/chapterImages/4"/>
<Chapter id="50739" filter="thumb=50739" tag="Airsick" index="5"
startTimeOffset="1884000" endTimeOffset="2262000" thumb="
/library/media/27753/chapterImages/5"/>
<Chapter id="50746" filter="thumb=50746" tag="Off Course" index="6"
startTimeOffset="2262000" endTimeOffset="2542000" thumb="
/library/media/27753/chapterImages/6"/>
<Chapter id="50747" filter="thumb=50747" tag="Okay, Panic" index="7"
startTimeOffset="2542000" endTimeOffset="2728000" thumb="
/library/media/27753/chapterImages/7"/>
<Chapter id="50745" filter="thumb=50745" tag="McCroskey" index="8"
startTimeOffset="2728000" endTimeOffset="2972000" thumb="
/library/media/27753/chapterImages/8"/>
<Chapter id="50751" filter="thumb=50751" tag="We Need You" index="9"
startTimeOffset="2972000" endTimeOffset="3307000" thumb="
/library/media/27753/chapterImages/9"/>
<Chapter id="50742" filter="thumb=50742" tag="Heating Up" index="10"
startTimeOffset="3307000" endTimeOffset="3608000" thumb="
/library/media/27753/chapterImages/10"/>
<Chapter id="50737" filter="thumb=50737" tag="A Bomb" index="11"
startTimeOffset="3608000" endTimeOffset="4026000" thumb="
/library/media/27753/chapterImages/11"/>
<Chapter id="50740" filter="thumb=50740" tag="Blow The Computer" index="12"
startTimeOffset="4026000" endTimeOffset="4247000" thumb="
/library/media/27753/chapterImages/12"/>
<Chapter id="50741" filter="thumb=50741" tag="Commander Murdock" index="13"
startTimeOffset="4247000" endTimeOffset="4707000" thumb="
/library/media/27753/chapterImages/13"/>
<Chapter id="50749" filter="thumb=50749" tag="Safe Landing" index="14"
startTimeOffset="4707000" endTimeOffset="4802000" thumb="
/library/media/27753/chapterImages/14"/>
<Chapter id="50750" filter="thumb=50750" tag="Thank You For Flying" index="
15" startTimeOffset="4802000" endTimeOffset="5056053" thumb="
/library/media/27753/chapterImages/15"/>
<Review id="33616" filter="art=33616" tag="Brian Costello" text="Classic
comedy with frequent sex and drug references." image="
rottentomatoes://image.review.fresh" link="
https://www.commonsensemedia.org/movie-reviews/airplane-ii-the-sequel"
source="Common Sense Media"/>
<Extras size="0"> </Extras>
<Related>
<Hub hubKey="/library/metadata/5418" key="
/library/sections/3/all?type=1&collection=65268&sort=originallyAvailableAt,year:nullsLast
" title="Airplane Collection" type="movie" hubIdentifier="
collection.related.3.1" context="hub.collection.related" size="1" more="1"
style="shelf">
<Video ratingKey="5418" key="/library/metadata/5418" guid="
com.plexapp.agents.imdb://tt0080339?lang=en" studio="Paramount" type="movie"
 title="Airplane!" contentRating="PG" summary="Alcoholic pilot, Ted Striker
has developed a fear of flying due to wartime trauma, but nevertheless
boards a passenger jet in an attempt to woo back his stewardess girlfriend.
Food poisoning decimates the passengers and crew, leaving it up to Striker
to land the plane with the help of a glue-sniffing air traffic controller
and Striker's vengeful former Air Force captain, who must both talk him
down." rating="9.7" audienceRating="8.9" year="1980" tagline="What's slower
than a speeding bullet, and able to hit tall buildings at a single bound?"
thumb="/library/metadata/5418/thumb/1571087819" art="
/library/metadata/5418/art/1571087819" duration="5262112"
originallyAvailableAt="1980-07-02" addedAt="1332558764" updatedAt="
1571087819" audienceRatingImage="rottentomatoes://image.rating.upright"
hasPremiumPrimaryExtra="1" ratingImage="rottentomatoes://image.rating.ripe">
<Media id="12536" duration="5262112" bitrate="10691" width="1920" height="
1080" aspectRatio="1.78" audioChannels="6" audioCodec="dca" videoCodec="h264
" videoResolution="1080" container="mkv" videoFrameRate="24p" audioProfile="
dts" videoProfile="high">
<Part id="27645" key="/library/parts/27645/1406352612/file.mkv" duration="
5262112" file="D:\Videos\Movies\Airplane! (1980)\Airplane! (1980).mkv" size
="7034151238" audioProfile="dts" container="mkv" deepAnalysisVersion="4"
requiredBandwidths="30287,26892,19839,14339,12057,11774,11774,11774"
videoProfile="high"/>
</Media>
<Genre tag="Comedy"/>
<Director tag="David Zucker"/>
<Director tag="Jerry Zucker"/>
<Director tag="Jim Abrahams"/>
<Writer tag="David Zucker"/>
<Writer tag="Jerry Zucker"/>
<Country tag="USA"/>
<Collection tag="Airplane"/>
<Role tag="Barbara Billingsley"/>
<Role tag="Craig Berenson"/>
<Role tag="Ethel Merman"/>
</Video>
</Hub>
</Related>
</Video>
</MediaContainer>

**Comment by eriecableguy** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<MediaContainer size="0"> </MediaContainer>


WHEN NOTHING IS PLAYING

**Comment by glitch452** [comment]
Okay, I took a look at the XML and it is a little different than what my Plex server produces for the `/status/sessions/` endpoint.  The XML data you sent seems to be missing some playback information like the `viewOffset` field in the main `video` tag.  It's also missing `session` and `player` tags.  It seems like this is data from the movie description endpoint, not the sessions endpoint?

I'm running Plex server version ` 1.18.9.2571` on `Windows`.  
Which platform and version are you running?

**Comment by TATUMTOT** [comment]
You should create an Plex Token just for the magic Mirror.

Is your server running with Encryption on it?

![image](https://user-images.githubusercontent.com/11933561/77973358-bf6ec000-72a8-11ea-9fe5-965af4f3b62b.png)


This is what I did. 
![image](https://user-images.githubusercontent.com/11933561/77973312-9e0dd400-72a8-11ea-86eb-838d82c1a1fa.png)

Create an Plex Authorization-Token for a custom App using python3 in a shell script
https://gist.github.com/fleXible/709e4583086b926646cb5304361693b4


I'm Here to assist if I can.
