### ISSUE TITLE
hideWhenNothingPlaying 

### ISSUE THREAD

**Issue by sly83910** [glitch452/MMM-PlexNowPlaying#7]
Hi, 

I try to add some configuration options but it don't work 

Ca you help me?

Thanks
![1](https://user-images.githubusercontent.com/61941483/100008254-79cdad00-2dcd-11eb-9b31-ace21d6c58a5.jpg)
![2](https://user-images.githubusercontent.com/61941483/100008256-7afeda00-2dcd-11eb-976c-cd49a6730ee9.JPG)

**Comment by glitch452** [comment]
It looks like you're missing a comma after the 'xPlexToken' value, which causes the file to be invalid JavaScript.

**Comment by sly83910** [comment]
thanks you very much and sorry for the noobs error.
Have a nice day
PS : have you a command to hide the mail of the plex account? 
Thanks

**Comment by TATUMTOT** [comment]
To hide the email address they would actually need to make an account name vs using their email as there account name. This can be found under the account tab in plex. https://app.plex.tv/desktop#!/settings/account

**Comment by sly83910** [comment]
I don't know if you understand my question.
I don't want see my account email here 
![1](https://user-images.githubusercontent.com/61941483/100204207-e0ed7d80-2f03-11eb-822d-3f20fdd12f18.jpg)

Thanks

**Comment by TATUMTOT** [comment]
Yep I know exactly what you want. Also try logging in with your username vs the email.

**Comment by glitch452** [comment]
Hi @sly83910, this module currently supports two ways to accomplish what you want.  

First, you can hide the user information (which includes both the avatar image and account name) with the `showUser` option, which can be set to `false`.  Here is an example with your config:
```javascript
config: {
    serverProtocol: "http",
    serverAddress: "192.168.1.202",
    serverPort: 32400,
    xPlexToken: "<your_token>",
    hideWhenNothingPlaying: true,
    showUser: false
}
```

The second option is to override the username with the `userNameFilter` option.  Which, I guess could be used to replace it with an empty string.  Here is an example: 

```javascript
config: {
    serverProtocol: "http",
    serverAddress: "192.168.1.202",
    serverPort: 32400,
    xPlexToken: "<your_token>",
    hideWhenNothingPlaying: true,
    userNameFilter: {
        "<account_email>": "<display_value>"
    }
}
```

In this example, the `<account_email>` value will be replaced with the `<display_value>` when the module renders the content.  The down-side of this method is that a filter is required for every email address or username that you want to hide.  Also note: any number of filters can be added to the `userNameFilter` list.

**Comment by sly83910** [comment]
Hi glitch 452,
The command showuser don't work but usernamefilter yes, juste avatar show up, it's ok for me !!

Thanks you both you can close this issue
