### ISSUE TITLE
Live TV poster not showing

### ISSUE THREAD

**Issue by colel83** [glitch452/MMM-PlexNowPlaying#8]
I am having an issue with the module not showing the poster image for users who are watching Live TV. It just shows a broken image placeholder. Is there any way to get the poster displayed for Live TV? I also tried setting the showPoster in config to false but that doesn't seem to do anything because posters for any content type were still displayed. Thanks for any help!

**Comment by glitch452** [comment]
Hey, thanks for the note.  It seems Plex has changed the way it reports live tv episodes on the endpoint.  I've updated the module to accommodate the change.  Please update to the latest version and that should resolve this issue!

**Comment by colel83** [comment]
Thanks for the module and for the quick fix!!!
